export const employeeData = [
    {
      id: 1,
      firstName: "Irtaza",
      email: "e@e.com",
      password: "123",
      taskCounts: {
        active: 2,
        newTask: 1,
        completed: 2,
        failed: 1,
      },
      tasks: [
        {
          active: true,
          newTask: true,
          completed: false,
          failed: false,
          taskTitle: "Update website",
          taskDescription: "Revamp the homepage design",
          taskDate: "2024-10-12",
          category: "Design",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Client meeting",
          taskDescription: "Discuss project requirements",
          taskDate: "2024-10-10",
          category: "Meeting",
        },
        {
          active: true,
          newTask: false,
          completed: false,
          failed: false,
          taskTitle: "Fix bugs",
          taskDescription: "Resolve bugs reported in issue tracker",
          taskDate: "2024-10-14",
          category: "Development",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Prepare budget report",
          taskDescription: "Compile financial data for Q3 review",
          taskDate: "2024-10-09",
          category: "Finance",
        },
        {
          active: false,
          newTask: false,
          completed: false,
          failed: true,
          taskTitle: "Email campaign",
          taskDescription: "Send promotional emails for the new product launch",
          taskDate: "2024-10-11",
          category: "Marketing",
        },
      ],
    },
    {
      id: 2,
      firstName: "Abdullah",
      email: "employee2@example.com",
      password: "123",
      taskCounts: {
        active: 1,
        newTask: 0,
        completed: 2,
        failed: 1,
      },
      tasks: [
        {
          active: true,
          newTask: false,
          completed: false,
          failed: false,
          taskTitle: "Database optimization",
          taskDescription: "Optimize queries for better performance",
          taskDate: "2024-10-11",
          category: "Database",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Design new feature",
          taskDescription: "Create mockups for the new feature",
          taskDate: "2024-10-09",
          category: "Design",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Run system checks",
          taskDescription: "Ensure the database servers are running smoothly",
          taskDate: "2024-10-08",
          category: "IT",
        },
        {
          active: false,
          newTask: false,
          completed: false,
          failed: true,
          taskTitle: "API integration",
          taskDescription: "Integrate third-party APIs into the application",
          taskDate: "2024-10-13",
          category: "Development",
        },
      ],
    },
    {
      id: 3,
      firstName: "Ayesha",
      email: "employee3@example.com",
      password: "123",
      taskCounts: {
        active: 2,
        newTask: 1,
        completed: 2,
        failed: 1,
      },
      tasks: [
        {
          active: true,
          newTask: true,
          completed: false,
          failed: false,
          taskTitle: "Prepare presentation",
          taskDescription: "Prepare slides for upcoming client presentation",
          taskDate: "2024-10-13",
          category: "Presentation",
        },
        {
          active: true,
          newTask: false,
          completed: false,
          failed: false,
          taskTitle: "Code review",
          taskDescription: "Review the codebase for optimization",
          taskDate: "2024-10-12",
          category: "Development",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Testing",
          taskDescription: "Test the latest build for bugs",
          taskDate: "2024-10-08",
          category: "QA",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Finalize project plan",
          taskDescription: "Complete the project scope documentation",
          taskDate: "2024-10-09",
          category: "Planning",
        },
        {
          active: false,
          newTask: false,
          completed: false,
          failed: true,
          taskTitle: "UI testing",
          taskDescription: "Identify UX issues in the interface design",
          taskDate: "2024-10-10",
          category: "QA",
        },
      ],
    },
    {
      id: 4,
      firstName: "Saad",
      email: "employee4@example.com",
      password: "123",
      taskCounts: {
        active: 2,
        newTask: 1,
        completed: 1,
        failed: 1,
      },
      tasks: [
        {
          active: true,
          newTask: true,
          completed: false,
          failed: false,
          taskTitle: "Write documentation",
          taskDescription: "Update the project documentation",
          taskDate: "2024-10-13",
          category: "Documentation",
        },
        {
          active: true,
          newTask: false,
          completed: false,
          failed: false,
          taskTitle: "Set up CI/CD",
          taskDescription: "Implement continuous integration pipeline",
          taskDate: "2024-10-11",
          category: "DevOps",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Prepare training material",
          taskDescription: "Develop slides and exercises for employee training",
          taskDate: "2024-10-12",
          category: "Training",
        },
        {
          active: false,
          newTask: false,
          completed: false,
          failed: true,
          taskTitle: "Server migration",
          taskDescription: "Migrate the application to a new hosting service",
          taskDate: "2024-10-10",
          category: "IT",
        },
      ],
    },
    {
      id: 5,
      firstName: "Saqib",
      email: "employee5@example.com",
      password: "123",
      taskCounts: {
        active: 2,
        newTask: 1,
        completed: 2,
        failed: 2,
      },
      tasks: [
        {
          active: false,
          newTask: false,
          completed: false,
          failed: true,
          taskTitle: "UI redesign",
          taskDescription: "Redesign the user interface for better UX",
          taskDate: "2024-10-14",
          category: "Design",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Deploy new build",
          taskDescription: "Deploy the latest build to production",
          taskDate: "2024-10-09",
          category: "DevOps",
        },
        {
          active: true,
          newTask: false,
          completed: false,
          failed: false,
          taskTitle: "Client feedback",
          taskDescription: "Gather feedback from clients after product launch",
          taskDate: "2024-10-12",
          category: "Support",
        },
        {
          active: false,
          newTask: false,
          completed: false,
          failed: true,
          taskTitle: "Network setup",
          taskDescription: "Resolve issues with office network configuration",
          taskDate: "2024-10-13",
          category: "IT",
        },
        {
          active: false,
          newTask: false,
          completed: true,
          failed: false,
          taskTitle: "Create wireframes",
          taskDescription: "Design wireframes for the mobile application",
          taskDate: "2024-10-08",
          category: "Design",
        },
      ],
    },
  ];
  


export const adminData = [
  {
    "id": 1,
    "firstName": "Admin", // Placeholder first name
    "email": "admin@me.com",
    "password": "123",
    "taskCounts": {
      "active": 0,
      "newTask": 0,
      "completed": 0,
      "failed": 0
    },
    "tasks": [] // Empty tasks array to maintain consistency
  }
];

